### ISSUE TITLE
Cannot read properties of undefined (reading 'id')

### ISSUE THREAD

**Issue by cesco69** [Hargne/html-creator#47]
```js
import htmlCreator from 'html-creator'; //  0.7.1

const html = new htmlCreator([{
        type: 'body',
        content: [
            {
                type: 'div',
                attributes: {
                    id: 'root',
                }
            }
        ]
}]);
html.document.addElementToId('root', [
        {
            type: 'div'
        }
])

// html2.document.findElementById('root') also cause same issue
```

error

```
Uncaught TypeError TypeError: Cannot read properties of undefined (reading 'id')
    at <anonymous> (\node_modules\html-creator\dist\index.js:32:109)
    at a (\node_modules\html-creator\dist\index.js:32:44)
    at findElementById (\node_modules\html-creator\dist\index.js:115:16)
    at addElementToTarget (\node_modules\html-creator\dist\index.js:87:32)
    at addElementToId (\node_modules\html-creator\dist\index.js:99:21)
```

If I install old version

```
npm i html-creator@0.4.4
```

it works!

**Comment by Hargne** [comment]
Hi,
Thanks for reporting. I will have a look at what is causing this error ASAP :)
